### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by OneScheer** [rempopo/CO25_Before_the_storm.eden#1]
1. Патрули достаточно близко к начальной точке расположены, может их обозначить на карте?
2.  ACOG у СЛ-а смотрится странно на АК. Я бы заменил российским либо другим зарубежным прицелом (типа Спектер)
3.  Зону Reinf вынести за зону операции, а то заспавнятся прям под носом. 
4. Так и должно быть?
`
#define us_w_o
["rhsusf_acc_compm4","rhsusf_acc_eotech_552","CUP_optic_ACOG_PIP","CUP_optic_ACOG_TA31_KF","CUP_optic_CompM2_Black","rhsusf_ach_helmet_ESS_ocp"]
#define us_w_h 
#define us_w_l`

**Comment by Comrade333** [comment]
1) Отметил на карте.
2) Поставил спектры.
3) Вынес.
4) Удалил лишнее.
